name: Build CI-Image
on:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./docker/wimoved-ci-env
          tags: ghcr.io/dasgoogle/wimoved-enterprise/wimoved-ci-env
