name: Build OpenWrt Image

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string
      version:
        type: string
        required: true
    secrets:
      ghtoken:
        required: true

jobs:
  build-env:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Extract metadata
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ghtoken }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: ./docker/openwrt-build-env
        tags: ghcr.io/dasgoogle/wimoved-enterprise/wimove-buildenv/${{ inputs.architecture }}:${{ env.BRANCH }}
        cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ inputs.architecture }}
        cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME-${{ inputs.architecture }}
        build-args: |
          TAG=${{ inputs.architecture }}
  build:
    runs-on: ubuntu-latest
    needs: build-env
    steps:
      - uses: actions/checkout@v3
      - name: Extract metadata
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghtoken }}
      - name: Build OpenWrt
        env:
          IMAGE: "ghcr.io/dasgoogle/wimoved-enterprise/wimove-buildenv/${{ inputs.architecture }}:${{ env.BRANCH }}"
          VERSION: "${{ inputs.version }}"
        run: chmod +x ./openwrt/build-openwrt.sh && ./openwrt/build-openwrt.sh
      - uses: actions/upload-artifact@v3
        with:
          name: wimove-${{ inputs.architecture }}
          path: out/*.ipk
