name: Run checks

on:
  push:

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: ghcr.io/dasGoogle/wimoved-enterprise/wimoved-ci-env:latest
    steps:
      - uses: actions/checkout@v3
      - name: Start CMake
        run: cmake CMakeLists.txt
      - name: Start formatting
        run: make format-check
  linting:
    runs-on: ubuntu-latest
    container: ghcr.io/dasgoogle/wimoved-enterprise/wimoved-ci-env:latest
    steps:
      - uses: actions/checkout@v3
      - name: Start CMake
        run: cmake CMakeLists.txt -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=0
      - name: Start linting
        run: make lint
  testing:
    runs-on: ubuntu-latest
    container: ghcr.io/dasgoogle/wimoved-enterprise/wimoved-ci-env:latest
    steps:
      - uses: actions/checkout@v3
      - name: Start CMake
        run: cmake CMakeLists.txt
      - name: Test
        run: make test
